# Generated by Django 4.1.4 on 2022-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='servicio_pago',
            field=models.CharField(max_length=30),
        ),
    ]
